### PR TITLE
Update KKBP_Exporter

### PR DESCRIPTION
**Pull request by MediaMoots**
v1.4
Changes:
Fixes https://github.com/FlailingFog/KK-Blender-Shader-Pack/issues/29#issuecomment-962505538
Attempts to fix https://github.com/FlailingFog/KK-Blender-Shader-Pack/pull/43#issuecomment-950522700

### CODE REVIEW

**Comment by MediaMoots** [comment]
v1.6
Should Actually fix https://github.com/FlailingFog/KK-Blender-Shader-Pack/pull/43#issuecomment-950522700
@Lexiii223 Feel free to test it if you want.
Fixed bone import issue

**Comment by FlailingFog** [comment]
Thanks for fixing these! I'll merge this now since the first two seem to be fixed.

The bone import issue is still present though.
Here's a card that shows off what I'm talking about. The bones for the right hair accessory wind up controlling both of the hair pieces.
Koikatu_F_20211107171037196_Haruno Chika

**Comment by MediaMoots** [comment]
Oh ok, ill try to fix the bone issue

**Comment by MediaMoots** [comment]
@FlailingFog 
image
: )

**Pull request merged**
