### PR TITLE
UV defaults

### PR DESCRIPTION
**Pull request by MediaMoots**
image
for PR #43

### CODE REVIEW

**Comment by MediaMoots** [comment]
Pubic hair uv default
image

**Comment by FlailingFog** [comment]
I'd rather not have the defaults for pubic hair go into the overlay 2 slot tbh, I want it to be used for general overlays / body paint. Managing the blend file on github is a little difficult so I'll merge this but I'm going to break the pubic hair out into the nsfw group after (and fix #41)

**Comment by MediaMoots** [comment]
> I'd rather not have the defaults for pubic hair go into the overlay 2 slot tbh

Totally agree, ill change the script to use the new slot.
Thank you.

**Comment by MediaMoots** [comment]
image
Under hair UV is not connected, haha

**Comment by MediaMoots** [comment]
image
This needs to be changed from Repeat to Clip.

**Pull request merged**
