### PR TITLE
Plugin Update

### LINKED ISSUE #56: KK Party Compatibility
Export_PMX folder for the character has all textures but no .PMX model. Have not been able to get it to output the .PMX no matter what I do.
(Using the V5.0 plugin in Koikatsu Party([Steam + After Party DLC] w/ HF Patch.)

### PR DESCRIPTION
**Pull request by MediaMoots**
Fixes #56

### CODE REVIEW

**Comment by MediaMoots** [comment]
v1.11 Waiting for testing https://github.com/FlailingFog/KK-Blender-Shader-Pack/issues/56#issuecomment-966808269

**Comment by MediaMoots** [comment]
v1.12 This should work 100% with KK Party.
If no issues are reported then this is ready to merge.

**Comment by FlailingFog** [comment]
Neat!
(I also gave you collaborator access in case you want to make any future plugin updates)

**Comment by MediaMoots** [comment]
Oh wow, thank you very much!

**Pull request merged**
