### PR TITLE
Automatic character export and processing

### PR DESCRIPTION
**Pull request by MediaMoots**
# What's new

## KKBP_Exporter Plugin
A brand new plugin that does away with GME and PMX Exporter
It's based off the PMX Exporter plugin.
Features:
- Only exports meshes that are visible in KK
- Exports all needed colors to a JSON file
- Exports all Textures
- Supports individual accessories/hair masks
- Does not break KK
- Uses BepinEX 5
- And much more.

## KKBP
- Fully automatic color import and conversion
- Imports blush, lip line, nsfw body textures, etc... 
- Automatic LUT import
- MainTex LUT conversion
- Bug fixes

# How to use?
Use blender 2.93 (idk if this is required, but it's what I'm using)

1. Install KKBP_Exporter.dll to KK
2. Export (No need to change blink/eye look/pose, plugin does it automatically)
image
3. Import with CATS, go through the hair separation process, merge duplicates (only the ones with .00X at the end) etc.
4. Import textures (step 2a) by selecting the folder with the model.pmx inside.
5. Do the same for step 2b
6. Tweak intensities and enjoy.

# Issues
#39 
#48 

~~#38~~ 
~~#40~~
~~#41~~
~~#42~~
~~#45~~
~~#46~~ 
~~#50~~
Sometimes the color for the top is wrong (Such as a sailor part), in that case you can just copy the colors from another part that is correct or just switch to use the Main Tex instead of the Color Mask

Please let me know if you find any bugs.

### CODE REVIEW

**Comment by FlailingFog** [comment]
Literally unbelievable, I tried it once and it works great.
Thank you again for doing this, you've pushed the export process to the endgame.

I'll look at it more in depth today and try to address your other issues

**Comment by MediaMoots** [comment]
Fixed:
#45
#46 
#38 

Plugin updates:
Export the kage color

KKBP updates:
Set the kage color

New issues:
#48

**Comment by FlailingFog** [comment]
Okay, here's my comments:
* The tongue color looks correct now, but the nipple colors are still off (except for that one card I pointed out). Again this doesn't personally bother me
* For dark clothes, the automatic dark color slider in blender needs to be disabled or you'll get the wrong colors
* The plugin tries to open the Documents folder in explorer after exporting instead of the PMX folder
* You've added tags that identify what material belongs to what mesh instance. This identification lets you combine the .00X materials automatically because there's no fear of combining the wrong materials together! I can add this later if you don't feel like doing it.
* Just an observation, the plugin seems to break the "All accs off" button on the right of the charamaker
* Another observation, I like that dynamic bones are disabled during export but I'm assuming when people make the card they take these into account, so on certain cards accessories will look a little off or clip into things after being imported to blender (like the bow in the one below). This doesn't bother me, but I guess it's something to note
86704918_p4

**Comment by MediaMoots** [comment]
Thanks for the comments!

> The tongue color looks correct now, but the nipple colors are still off (except for that one card I pointed out). Again this doesn't personally bother me

Are you using blender 2.93?
I guess it's not a big deal, it might work for some ppl but not for others.
They can always set the color themselves.

> For dark clothes, the automatic dark color slider in blender needs to be disabled or you'll get the wrong colors

Ok thanks!

> You've added tags that identify what material belongs to what mesh instance. This identification lets you combine the .00X materials automatically because there's no fear of combining the wrong materials together! I can add this later if you don't feel like doing it.

Good point, I'll try and script it, if not, then feel free to do that.

> Just an observation, the plugin seems to break the "All accs off" button on the right of the charamaker

I don't have that button?
image
image
The show acc tick boxes work for me.

**Comment by MediaMoots** [comment]
New update should fix:

> For dark clothes, the automatic dark color slider in blender needs to be disabled or you'll get the wrong colors

> The plugin tries to open the Documents folder in explorer after exporting instead of the PMX folder

**Comment by FlailingFog** [comment]
>Are you using blender 2.93?

I'm on 2.93.0. I'll update to see if it makes a difference

>I don't have that button?

This one?
image

**Comment by MediaMoots** [comment]
> This one?

Hmm, I don't have it, maybe I'm lacking a plugin?
I think you can use the acc checkboxes on the right to get the same effect.

**Comment by MediaMoots** [comment]
> Another observation, I like that dynamic bones are disabled during export but I'm assuming when people make the card they take these into account, so on certain cards accessories will look a little off or clip into things after being imported to blender (like the bow in the one below). This doesn't bother me, but I guess it's something to note

So, after a bit of digging here's the issue:
The plugin does not disable dynamic bones, rather, it can't/doesn't export bone rotations.
I don't know how to fix this, so I guess it's just something that users need to take note of.

**Comment by miyabi-95** [comment]
this looks so intriguing!! thanks for offering a faster alternative, i look forward to testing it out this week :)

**Comment by MediaMoots** [comment]
New Plugin:
Exports pattern colors correctly

New Scripts:
Imports and applies clothing patterns

**Comment by FlailingFog** [comment]
I've got a few extra notes:
* Weird, but updating to 2.93.4 fixed the color issue for me
* I broke your edits to importeverything.py because I renamed "NipL.001" in the Template Body's NSFW group to something else. It should be "Genital" now
* The pattern import didn't seem to work for me on Chika. It was imported into Blender but not applied
* I'm pretty sure I shared a Megumin card with you earlier. It turns out that particular card has a VERY long material name for some reason, so with the material name plus the instance tag plus the "_MainTex_ColoredTex" tag results in the image name being cut off after you import it into blender because blender imposes a character limit. Could you reduce the length of this tag to something shorter, like "_MainTex_Col" or "_ColoredTex" or something?
* Would it be possible to apply the warm Sunset LUT to the body and face materials instead of the cold Night LUT?

>New update should fix:

Works good now!

>it can't/doesn't export bone rotations.

Just found out that you can manually rotate the bones in blender to look correct, apply the current armature modifier rotations as a shapekey, and then apply the bone rotations in pose mode as a rest post, so this isn't a big deal at all

**Comment by MediaMoots** [comment]
> Weird, but updating to 2.93.4 fixed the color issue for me

Nice, that's great!

> The pattern import didn't seem to work for me on Chika. It was imported into Blender but not applied

Oh no, not another bug.
This is what Chika looks like for me, what about for you?
image

> I'm pretty sure I shared a Megumin card with you earlier.

Good catch, I'll try to fix it.

> Would it be possible to apply the warm Sunset LUT to the body and face materials instead of the cold Night LUT?

Ok.

**Comment by MediaMoots** [comment]
New update

Fixed: 
Long names
Use the sunset lut

**Comment by FlailingFog** [comment]
> This is what Chika looks like for me, what about for you?

Sorry, I realized I installed the new version without reloading blender, so it was using the old one when I tried it originally. This works for me

**Comment by MediaMoots** [comment]
Ah, nice

**Comment by FlailingFog** [comment]
> Use the sunset lut

To be honest I don't like how this looks compared to the night LUT...
Sorry for being picky.

Could you also add the exporter dll with the stock armature?
And if you're okay with leaving the remaining issues for later, I can merge this now and we can work from there.

**Comment by MediaMoots** [comment]
> To be honest I don't like how this looks compared to the night LUT...

No problem, so what should we use?
Day lut for both light and dark?

> Could you also add the exporter dll with the stock armature?

ok

> I can merge this now and we can work from there

I think that's fine, let me make sure it all works one more time, then we can merge.

**Comment by MediaMoots** [comment]
Ok, the latest commits should be final.

Feel free to merge.

When I need to make changes do I just open a new PR?

**Comment by FlailingFog** [comment]
It's been merged, thanks a ton for adding these features! I really thought what I currently had was as good as it was going to get, so I'm very thankful for your work.

I don't know if you can make edits to an already merged PR, but I'll accept either way if you can/can't

**Comment by MediaMoots** [comment]
Very cool, thanks!

Feel free to let me know if you find bugs.

**Comment by MediaMoots** [comment]
> @MediaMoots Hey I'm having trouble getting the KKBP_Exporter Plugin to actually export a pmx file. It exports all the textures and then just doesn't create a pmx file. It's not even working on a base model with no accessories. Any assistance would be much appreciated. Any chance the exporting process generates a log I can investigate?
> 
> Edit: Found the log file and I seem to be getting this error
> 
> > System.MissingFieldException: Field '.ChaClothesComponent.rendNormal03' not found.
> > at PmxBuilder.ExportSpecialTextures () [0x00000] in :0 System.MissingFieldException: Field '.ChaClothesComponent.rendNormal03' not found.
> > at PmxBuilder.GatherCharacterColors () [0x00000] in :0
> 
> I'm curious if my install is messed up or something.

Oh yeah, it seems you do not have the darkness dlc?

**Comment by MediaMoots** [comment]
> Still having the same issue. image I'm pretty sure it's because this clothing item has it's material set as cf_m_body for whatever reason. It's not a huge issue I can easily remove the item and grab the right texture. Just wanted to let you know about textures overwriting.

Please try PR #61

**Comment by Lexiii223** [comment]
> If you have time, please try out PR #61

Works great now! Thank you!

**Pull request merged**
